version: '2.3'
services:
  mysql:
    image: mysql:5.7.28
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  am-analytics-worker:
    image: wso2/wso2am-analytics-worker:3.0.0
    ports:
      - "9091:9091"
      - "9444:9444"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9444"]
      interval: 10s
      timeout: 120s
      start_period: 120s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./apim-analytics-worker:/home/wso2carbon/wso2-config-volume
  is-as-km:
    image: wso2/wso2is-km:5.9.0
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9443"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 15
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./is-as-km/config:/home/wso2carbon/wso2-config-volume
      - ./is-as-km/artifact:/home/wso2carbon/wso2-artifact-volume
    ports:
      - "9765:9763"
      - "9445:9443"
  api-manager:
    image: wso2/wso2am:3.0.0
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9443"]
      interval: 10s
      timeout: 120s
      start_period: 100s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy
      am-analytics-worker:
        condition: service_healthy
      is-as-km:
        condition: service_healthy
    volumes:
      - ./apim/config:/home/wso2carbon/wso2-config-volume
      - ./apim/artifact:/home/wso2carbon/wso2-artifact-volume
    ports:
      - "9763:9763"
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
  am-analytics-dashboard:
    image: wso2/wso2am-analytics-dashboard:3.0.0
    ports:
      - "9643:9643"
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9643"]
      interval: 10s
      timeout: 120s
      retries: 5
      start_period: 100s
    depends_on:
      mysql:
        condition: service_healthy
      api-manager:
        condition: service_healthy
    volumes:
      - ./apim-analytics-dashboard/config:/home/wso2carbon/wso2-config-volume
      - ./apim-analytics-dashboard/artifact:/home/wso2carbon/wso2-artifact-volume
